'use client';

import {useEffect,useState} from 'react';
import {Aperture,ArrowRight,BarChart3,Bot,Check,ChevronRight,CircleDot,GitCompareArrows,Layers3,Lightbulb,LoaderCircle,MessageSquareText,ShieldAlert,X} from 'lucide-react';

type RecordRow={id:string;sourceStyle:string;language:string;userText:string;contentType:string;targetPhoto:string;retrievalPurpose:string;rememberedClues:string;explicitlyForgotten:string;memoryConfidence:string;queriesInOrder:string;journey:string;observedProblemOrSuccess:string;workaround:string;outcome:string;targetAvailability:string;scope:string;scenarioPattern:string;primaryProblemFamily:string;problemSubtype:string;retrievalBehaviour:string;classificationConfidence:string;interpretationLimit:string};
type Answer={insufficient?:boolean;finding:string;breakdown:{label:string;value:string}[];interpretation:string;confidence:string;limitations:string;evidence:RecordRow[];matched?:number};
type View='overview'|'compare'|'ask'|'opportunities';

const families=['Remembering and expressing clues','Connecting memory to searchable evidence','Narrowing and correcting the search','Exploring and recognising candidates','Photo availability and library scope'];
const colors:Record<string,string>={'Remembering and expressing clues':'#ff709f','Connecting memory to searchable evidence':'#43e6f2','Narrowing and correcting the search':'#ffc56f','Exploring and recognising candidates':'#b098ff','Photo availability and library scope':'#72eab3','Unknown / insufficient evidence':'#8fa0b8','No primary failure observed':'#eef3fa'};
const short:Record<string,string>={'Remembering and expressing clues':'Expressing clues','Connecting memory to searchable evidence':'Grounding memory','Narrowing and correcting the search':'Narrowing search','Exploring and recognising candidates':'Recognising candidates','Photo availability and library scope':'Library scope','Unknown / insufficient evidence':'Insufficient evidence','No primary failure observed':'No failure observed'};
const nav=[{id:'overview',label:'Research overview',icon:BarChart3},{id:'compare',label:'Problem comparison',icon:GitCompareArrows},{id:'ask',label:'Ask the research',icon:MessageSquareText},{id:'opportunities',label:'Opportunity view',icon:Lightbulb}] as const;
const prompts=['What information do users remember when they cannot remember the date?','How do English and Hinglish users formulate retrieval attempts differently?','How do the five primary problem families differ?','Which problem families have the highest abandonment in this dataset?','Which problem families have the highest exact-photo success rate?','What new clues emerge during the retrieval process?','Which problems occur before candidates are retrieved, and which occur after?','Which accounts do not fit the taxonomy cleanly?'];
const stages=['Retrieving relevant episodes','Calculating reproducible breakdowns','Synthesising evidence and limitations'];
const opportunityCopy:Record<string,{situation:string;problem:string;stage:string;hypothesis:string;uncertainty:string;next:string}>={
 'Remembering and expressing clues':{situation:'start with a vivid but incomplete memory',problem:'cannot turn it into a discriminating query',stage:'Recall → query formation',hypothesis:'Structured clue elicitation may make partial memory more actionable.',uncertainty:'Whether users can provide more clues when prompted.',next:'Observe live query formulation and test which prompts unlock usable clues.'},
 'Connecting memory to searchable evidence':{situation:'remember meaning or a clear detail',problem:'cannot connect that memory to returned evidence',stage:'Query → candidate retrieval',hypothesis:'Exposing how a clue maps to candidates may support correction.',uncertainty:'The account cannot establish indexing or model failure.',next:'Run instrumented retrieval tests using the same stated clues.'},
 'Narrowing and correcting the search':{situation:'receive broad or incorrectly constrained results',problem:'cannot efficiently refine the candidate space',stage:'Results → refinement',hypothesis:'Progressive, reversible narrowing may reduce dead ends.',uncertainty:'Which refinement dimensions users understand and trust.',next:'Prototype date, place, person, and visual-detail refinements.'},
 'Exploring and recognising candidates':{situation:'reach potentially relevant candidates',problem:'struggle to inspect or recognise the exact photo',stage:'Candidate inspection',hypothesis:'Better comparison and navigation may reduce inspection burden.',uncertainty:'Whether the target was actually present in the viewed set.',next:'Measure recognition time across result density and thumbnail treatments.'},
 'Photo availability and library scope':{situation:'search the current Google Photos library',problem:'the target may live elsewhere or in another account',stage:'Scope confirmation',hypothesis:'Earlier scope checks may prevent wasted search effort.',uncertainty:'Availability is often unknown rather than confirmed absent.',next:'Study account switching, cross-app origin, backup state, and provenance.'}
};

const tally=(rows:RecordRow[],key:keyof RecordRow)=>Object.entries(rows.reduce<Record<string,number>>((a,r)=>(a[String(r[key])]=(a[String(r[key])]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);
const percent=(n:number,d:number)=>d?Math.round(n/d*100):0;
const human=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase());

function StatBar({label,value,total,color='#43e6f2'}:{label:string;value:number;total:number;color?:string}){return <div className="statbar"><div><span>{label}</span><strong>{value}<small>{percent(value,total)}%</small></strong></div><i><b style={{width:`${percent(value,total)}%`,background:color}}/></i></div>}

function CompareCard({family,records}:{family:string;records:RecordRow[]}){const rows=records.filter(r=>r.primaryProblemFamily===family);const top=(key:keyof RecordRow,n=3)=>tally(rows,key).slice(0,n);return <article className="compare-card" style={{'--family':colors[family]} as React.CSSProperties}><div className="family-title"><span/><div><small>PRIMARY PROBLEM FAMILY</small><h2>{family}</h2></div></div><div className="compare-kpis"><div><strong>{rows.length}</strong><span>records · {percent(rows.length,records.length)}%</span></div><div><strong>{percent(rows.filter(r=>r.outcome==='Exact photo found').length,rows.length)}%</strong><span>exact-photo success</span></div><div><strong>{percent(rows.filter(r=>r.outcome==='Abandoned').length,rows.length)}%</strong><span>abandonment</span></div></div><Detail label="Common subtypes" values={top('problemSubtype')}/><Detail label="Retrieval behaviours" values={top('retrievalBehaviour')}/><Detail label="Forgotten information" values={top('explicitlyForgotten')}/><Detail label="Content represented" values={top('contentType',4)}/><Detail label="Language split" values={top('language')}/><Detail label="Classification confidence" values={top('classificationConfidence')}/><div className="text-evidence"><h3>Remembered-clue examples</h3>{rows.slice(0,3).map(r=><p key={r.id}>{r.rememberedClues}</p>)}</div><div className="text-evidence"><h3>Observed workarounds</h3>{rows.filter(r=>r.workaround&&r.workaround!=='not needed').slice(0,3).map(r=><p key={r.id}>{r.workaround}</p>)}</div></article>}
function Detail({label,values}:{label:string;values:[string,number][]}){return <section className="detail"><h3>{label}</h3>{values.map(([name,count])=><div key={name}><span>{human(name)}</span><strong>{count}</strong></div>)}</section>}

export default function Home(){
 const[view,setView]=useState<View>('overview');const[records,setRecords]=useState<RecordRow[]>([]);const[selected,setSelected]=useState<RecordRow|null>(null);const[compareA,setCompareA]=useState(families[0]);const[compareB,setCompareB]=useState(families[3]);
 const[question,setQuestion]=useState(prompts[0]);const[answer,setAnswer]=useState<Answer|null>(null);const[loading,setLoading]=useState(false);const[stage,setStage]=useState(0);
 useEffect(()=>{fetch('/api/evidence').then(r=>r.json()).then(data=>setRecords(data.records||[]));},[]);
 const familyCounts=tally(records,'primaryProblemFamily');const outcomes=tally(records,'outcome');const content=tally(records,'contentType');const unknown=records.filter(r=>r.primaryProblemFamily==='Unknown / insufficient evidence').length;
 async function analyze(q=question){setQuestion(q);setLoading(true);setAnswer(null);setStage(0);setTimeout(()=>setStage(1),550);setTimeout(()=>setStage(2),1100);try{const[data]=await Promise.all([fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}).then(r=>r.json()),new Promise(res=>setTimeout(res,1650))]);setAnswer(data);}finally{setLoading(false);}}
 return <main className="app-shell"><aside className="sidebar"><button className="brand" onClick={()=>setView('overview')}><span className="brand-mark"><Aperture size={23}/></span><span>RECALL<strong>Photo Retrieval Research</strong></span></button><nav>{nav.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}><item.icon size={18}/><span>{item.label}</span><ChevronRight size={15}/></button>)}</nav></aside>
 <section className="workspace"><header className="topbar"><div><span className="live-dot"/> DATASET READY</div><div className="top-meta"><span>300 accounts indexed</span><span>5 problem families</span></div></header>
 {view==='overview'&&<><div className="page-heading"><div><span className="kicker">PHOTO RETRIEVAL DISCOVERY ENGINE</span><h1>Understand where remembered-photo retrieval breaks.</h1><p>A structured PM research workspace for comparing retrieval mechanisms, inspecting full journeys, and identifying evidence-backed areas for further research.</p></div><button className="primary" onClick={()=>setView('ask')}><Bot size={18}/> Ask the research</button></div>
 <div className="metric-grid"><article><span>ACCOUNTS ANALYSED</span><strong>{records.length||'—'}</strong><small>Complete retrieval episodes</small></article><article><span>EXACT PHOTO FOUND</span><strong>{records.filter(r=>r.outcome==='Exact photo found').length}</strong><small>{percent(records.filter(r=>r.outcome==='Exact photo found').length,records.length)}% within this corpus</small></article><article><span>UNKNOWN FAMILY</span><strong>{unknown}</strong><small>Unforced classifications</small></article></div>
 <div className="overview-grid"><section className="panel"><div className="panel-head"><div><span className="kicker">PROBLEM TAXONOMY</span><h2>Five mechanisms, kept analytically distinct</h2></div><small>n = 300</small></div>{familyCounts.map(([name,count])=><button className="family-row" key={name} onClick={()=>{if(families.includes(name)){setCompareA(name);setView('compare')}}}><span className="family-dot" style={{background:colors[name]}}/><span><strong>{short[name]||name}</strong><small>{name}</small></span><i><b style={{width:`${percent(count,records.length)}%`,background:colors[name]}}/></i><strong>{count}</strong><small>{percent(count,records.length)}%</small></button>)}</section>
 <section className="panel"><span className="kicker">RETRIEVAL OUTCOMES</span><h2>Outcome is separate from problem type</h2>{outcomes.map(([name,count])=><StatBar key={name} label={name} value={count} total={records.length} color={name==='Exact photo found'?'#72eab3':name==='Abandoned'?'#ff709f':'#43e6f2'}/>)}</section></div>
 <div className="overview-grid lower"><section className="panel"><span className="kicker">CONTENT MIX</span><h2>Targets span personal and functional memories</h2><div className="chip-cloud">{content.map(([name,count])=><span key={name}>{human(name)} <strong>{count}</strong></span>)}</div></section><section className="panel journey-model"><span className="kicker">EPISODE MODEL</span><h2>Every account follows the same evidence chain</h2><div className="journey-line"><span>Target</span><ArrowRight/><span>Purpose</span><ArrowRight/><span>Clues</span><ArrowRight/><span>Actions</span><ArrowRight/><span>Outcome</span></div></section></div></>}

 {view==='compare'&&<><PageHead kicker="SIDE-BY-SIDE ANALYSIS" title="Problem comparison" text="Compare mechanisms rather than combining every unsuccessful retrieval into a single search-quality issue."/><div className="compare-controls"><label>LEFT FAMILY<select value={compareA} onChange={e=>setCompareA(e.target.value)}>{families.map(f=><option key={f}>{f}</option>)}</select></label><GitCompareArrows/><label>RIGHT FAMILY<select value={compareB} onChange={e=>setCompareB(e.target.value)}>{families.map(f=><option key={f}>{f}</option>)}</select></label></div><div className="comparison-grid"><CompareCard family={compareA} records={records}/><CompareCard family={compareB} records={records}/></div></>}

 {view==='ask'&&<><PageHead kicker="DATASET-GROUNDED SYNTHESIS" title="Ask the research" text="Ask a retrieval question. The engine calculates counts deterministically, cites record IDs, and states uncertainty."/><div className="ask-layout"><section><div className="ask-box"><MessageSquareText size={20}/><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!loading&&analyze()}/><button onClick={()=>analyze()} disabled={loading}>Analyse</button></div><div className="prompt-grid">{prompts.map((prompt,index)=><button key={prompt} onClick={()=>!loading&&analyze(prompt)}><span>0{index+1}</span><strong>{prompt}</strong><ArrowRight size={15}/></button>)}</div></section><section className="answer-zone">{loading?<div className="loader-card"><div className="loader-orbit"><LoaderCircle size={30}/></div><h2>Analysing retrieval episodes</h2><div className="stage-list">{stages.map((item,index)=><div key={item} className={index<stage?'done':index===stage?'current':''}>{index<stage?<Check size={15}/>:<CircleDot size={15}/>}<span>{item}</span></div>)}</div></div>:answer?<div className="answer-card"><div className="analyst"><Bot size={19}/> RECALL RESEARCH SYNTHESIS</div><h2>Finding</h2><p className="lead">{answer.finding}</p>{answer.breakdown.length>0&&<><h3>Comparison or breakdown</h3><div className="breakdown">{answer.breakdown.map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></>}<h3>Supporting records</h3><div className="supporting">{answer.evidence.map(row=><button key={row.id} onClick={()=>setSelected(row)}><strong>{row.id}</strong><blockquote>“{row.userText}”</blockquote></button>)}</div><h3>Interpretation</h3><p>{answer.interpretation}</p><div className="limitation"><strong>Confidence: {answer.confidence}</strong><span>{answer.limitations}</span></div></div>:<div className="empty-card"><Layers3 size={36}/><h2>Your synthesis will appear here</h2><p>Select one of eight curated questions or ask a dataset-grounded question.</p></div>}</section></div></>}

 {view==='opportunities'&&<><PageHead kicker="EVIDENCE → HYPOTHESIS" title="Opportunity view" text="These are research directions, not feature recommendations. Each keeps the uncertainty and next evidence need visible."/><div className="opportunity-grid">{families.map((family,index)=>{const rows=records.filter(r=>r.primaryProblemFamily===family),meta=opportunityCopy[family],leading=tally(rows,'outcome')[0];return <article className="opportunity-card" key={family} style={{'--family':colors[family]} as React.CSSProperties}><div className="opportunity-no">0{index+1}</div><span className="opportunity-family">{family}</span><h2>Help users who {meta.situation} overcome {meta.problem} so that they can make retrieval progress.</h2><dl><div><dt>User situation</dt><dd>{meta.situation}</dd></div><div><dt>Retrieval problem</dt><dd>{meta.problem}</dd></div><div><dt>Evidence pattern</dt><dd>{rows.length} accounts; leading outcome: {leading?.[0]} ({leading?.[1]}).</dd></div><div><dt>Affected journey stage</dt><dd>{meta.stage}</dd></div><div><dt>Current workaround</dt><dd>{rows.find(r=>r.workaround&&r.workaround!=='not needed')?.workaround||'No confirmed workaround stated.'}</dd></div><div><dt>Outcome impact</dt><dd>{percent(rows.filter(r=>r.outcome==='Abandoned'||r.outcome==='Unresolved').length,rows.length)}% abandoned or unresolved in this corpus.</dd></div><div><dt>Recoverability hypothesis</dt><dd>{meta.hypothesis}</dd></div><div><dt>Important uncertainty</dt><dd>{meta.uncertainty}</dd></div><div><dt>Research needed next</dt><dd>{meta.next}</dd></div></dl></article>})}</div></>}
 </section>{selected&&<RecordDrawer row={selected} close={()=>setSelected(null)}/>}</main>;
}

function PageHead({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="page-heading compact"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></div></div>}
function RecordDrawer({row,close}:{row:RecordRow;close:()=>void}){const factual=[['Target photo',row.targetPhoto],['Retrieval purpose',row.retrievalPurpose],['Remembered clues',row.rememberedClues],['Explicitly forgotten',row.explicitlyForgotten],['Queries in order',row.queriesInOrder],['Journey / actions',row.journey],['Observed problem or success',row.observedProblemOrSuccess],['Workaround',row.workaround],['Outcome',row.outcome],['Target availability',row.targetAvailability]];return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={close}><X size={20}/></button><span className="record-badge">{row.id} · {row.language} · {human(row.contentType)}</span><h2>{row.targetPhoto}</h2><p>{row.sourceStyle}</p><h3>Account text · observed evidence</h3><blockquote>“{row.userText}”</blockquote><div className="fact-grid">{factual.map(([label,value])=><div key={label}><span>{label}</span><strong>{value||'Not stated'}</strong></div>)}</div><h3>Engine classification · inferred</h3><div className="classification"><span style={{borderColor:colors[row.primaryProblemFamily]}}>{row.primaryProblemFamily}</span><span>{row.problemSubtype}</span><span>{row.retrievalBehaviour}</span><span>{row.classificationConfidence} confidence</span></div><div className="drawer-limit"><ShieldAlert size={17}/><div><strong>Interpretation limitation</strong><span>{row.interpretationLimit}</span></div></div></aside></div>}
